import { useSettingsStore } from '../store/settings';
import type { Language } from './translations';

export const UI_KEYS = [
  'graph', 'message', 'author', 'date', 'hash', 'loading', 'idle', 'copyCommand', 'clear',
  'collapse', 'expand', 'terminal', 'noOperations', 'gitCommand', 'output', 'history', 'problems',
  'executeHint', 'operationInfo', 'stageChanges', 'stageChangesDesc', 'gitFlow', 'affectedFiles',
  'noAffectedFiles', 'status', 'upToDate', 'aheadBehind', 'stage', 'unstage', 'discard', 'confirm',
  'cancel', 'checkout', 'localBranches', 'remoteBranches', 'tracking', 'deleteQuestion', 'force',
  'renameSuccess', 'renameFailed', 'deleteSuccess', 'deleteFailed', 'checkoutFailed', 'merge',
  'newBranch', 'stashes', 'stashAllChanges', 'noStashes', 'noStashesDesc', 'apply', 'pop', 'drop',
  'stashSaveSuccess', 'stashSaveFailed', 'applyFailed', 'popFailed', 'dropSuccess', 'dropFailed',
  'tags', 'tagCount', 'noTags', 'tagHint', 'lightweightTag', 'remotes', 'remoteCount',
  'noRemotes', 'remoteHint', 'fetchUrl', 'pushUrl', 'notConfigured', 'successful', 'failed',
  'commitSuccess', 'pushSuccess', 'pushFailed', 'commitFailed', 'undo', 'undoConfirm', 'undoSuccess', 'undoFailed',
] as const;

export type UiKey = typeof UI_KEYS[number];
type UiDictionary = Record<UiKey, string>;

export const UI_TRANSLATIONS: Record<Language, UiDictionary> = {
  English: {
    graph: 'Graph', message: 'Message', author: 'Author', date: 'Date', hash: 'Hash', loading: 'Loading...', idle: 'Idle', copyCommand: 'Copy command', clear: 'Clear', collapse: 'Collapse', expand: 'Expand', terminal: 'Terminal', noOperations: 'Run a Git action to see the CLI output here.', gitCommand: 'Git Command', output: 'Output', history: 'History', problems: 'Problems', executeHint: 'The Git command will be executed when you press Execute (Enter)', operationInfo: 'Operation Info', stageChanges: 'Stage Changes', stageChangesDesc: 'Move changes from the Working Tree to the Staging Area (index).', gitFlow: 'Git Flow', affectedFiles: 'Affected Files', noAffectedFiles: 'No affected files', status: 'Status', upToDate: 'Up to date', aheadBehind: '{ahead} ahead, {behind} behind', stage: 'Stage', unstage: 'Unstage', discard: 'Discard', confirm: 'Confirm', cancel: 'Cancel', checkout: 'Checkout', localBranches: 'Local Branches', remoteBranches: 'Remote Branches', tracking: 'tracking', deleteQuestion: 'Delete?', force: 'Force', renameSuccess: 'Rename successful', renameFailed: 'Rename failed', deleteSuccess: 'Branch deleted', deleteFailed: 'Delete failed', checkoutFailed: 'Checkout failed', merge: 'Merge', newBranch: 'New Branch', stashes: 'Stashes', stashAllChanges: 'Stash All Changes', noStashes: 'No stashes found', noStashesDesc: "You haven't stashed any changes yet.", apply: 'Apply', pop: 'Pop', drop: 'Drop', stashSaveSuccess: 'Changes stashed', stashSaveFailed: 'Stash failed', applyFailed: 'Apply failed', popFailed: 'Pop failed', dropSuccess: 'Stash deleted', dropFailed: 'Delete stash failed', tags: 'Tags', tagCount: '{count} tags', noTags: 'No tags found', tagHint: 'Create a tag from a commit to mark a release point.', lightweightTag: 'Lightweight tag', remotes: 'Remotes', remoteCount: '{count} remotes', noRemotes: 'No remotes configured', remoteHint: 'Add a remote to fetch and push this repository.', fetchUrl: 'Fetch', pushUrl: 'Push', notConfigured: 'Not configured', successful: 'successful', failed: 'failed', commitSuccess: 'Commit successful', pushSuccess: 'Push successful', pushFailed: 'Push failed', commitFailed: 'Commit failed', undo: 'Undo', undoConfirm: 'Undo the last commit and keep changes in the working directory?', undoSuccess: 'Undo successful', undoFailed: 'Undo failed',
  },
  Vietnamese: {
    graph: 'Sơ đồ', message: 'Thông điệp', author: 'Tác giả', date: 'Ngày', hash: 'Mã hash', loading: 'Đang tải...', idle: 'Đang chờ', copyCommand: 'Sao chép lệnh', clear: 'Xóa', collapse: 'Thu gọn', expand: 'Mở rộng', terminal: 'Terminal', noOperations: 'Thực hiện thao tác Git để xem output CLI tại đây.', gitCommand: 'Lệnh Git', output: 'Output', history: 'Lịch sử', problems: 'Vấn đề', executeHint: 'Lệnh Git sẽ được thực thi khi bạn nhấn Execute (Enter)', operationInfo: 'Thông tin thao tác', stageChanges: 'Stage thay đổi', stageChangesDesc: 'Di chuyển thay đổi từ Working Tree vào Staging Area (index).', gitFlow: 'Luồng Git', affectedFiles: 'Tệp bị ảnh hưởng', noAffectedFiles: 'Không có tệp bị ảnh hưởng', status: 'Trạng thái', upToDate: 'Đã cập nhật', aheadBehind: 'trước {ahead}, sau {behind}', stage: 'Stage', unstage: 'Unstage', discard: 'Hủy thay đổi', confirm: 'Xác nhận', cancel: 'Hủy', checkout: 'Checkout', localBranches: 'Nhánh local', remoteBranches: 'Nhánh remote', tracking: 'theo dõi', deleteQuestion: 'Xóa?', force: 'Bắt buộc', renameSuccess: 'Đổi tên thành công', renameFailed: 'Đổi tên thất bại', deleteSuccess: 'Đã xóa nhánh', deleteFailed: 'Xóa thất bại', checkoutFailed: 'Checkout thất bại', merge: 'Merge', newBranch: 'Nhánh mới', stashes: 'Stash', stashAllChanges: 'Stash toàn bộ thay đổi', noStashes: 'Chưa có stash', noStashesDesc: 'Bạn chưa lưu thay đổi nào vào stash.', apply: 'Apply', pop: 'Pop', drop: 'Xóa', stashSaveSuccess: 'Đã stash thay đổi', stashSaveFailed: 'Stash thất bại', applyFailed: 'Apply thất bại', popFailed: 'Pop thất bại', dropSuccess: 'Đã xóa stash', dropFailed: 'Xóa stash thất bại', tags: 'Thẻ', tagCount: '{count} thẻ', noTags: 'Chưa có thẻ', tagHint: 'Tạo thẻ từ một commit để đánh dấu mốc phát hành.', lightweightTag: 'Thẻ nhẹ', remotes: 'Remote', remoteCount: '{count} remote', noRemotes: 'Chưa cấu hình remote', remoteHint: 'Thêm remote để fetch và push repository này.', fetchUrl: 'Fetch', pushUrl: 'Push', notConfigured: 'Chưa cấu hình', successful: 'thành công', failed: 'thất bại', commitSuccess: 'Commit thành công', pushSuccess: 'Push thành công', pushFailed: 'Push thất bại', commitFailed: 'Commit thất bại', undo: 'Hoàn tác', undoConfirm: 'Hoàn tác commit cuối và giữ thay đổi trong thư mục làm việc?', undoSuccess: 'Hoàn tác thành công', undoFailed: 'Hoàn tác thất bại',
  },
  Japanese: {
    graph: 'グラフ', message: 'メッセージ', author: '作成者', date: '日付', hash: 'ハッシュ', loading: '読み込み中...', idle: '待機中', copyCommand: 'コマンドをコピー', clear: 'クリア', collapse: '折りたたむ', expand: '展開', terminal: 'ターミナル', noOperations: 'Git操作を実行するとCLI出力が表示されます。', gitCommand: 'Gitコマンド', output: '出力', history: '履歴', problems: '問題', executeHint: 'Execute (Enter)を押すとGitコマンドを実行します', operationInfo: '操作情報', stageChanges: '変更をステージ', stageChangesDesc: 'Working TreeからStaging Area (index)へ変更を移動します。', gitFlow: 'Gitフロー', affectedFiles: '影響を受けるファイル', noAffectedFiles: '影響を受けるファイルはありません', status: '状態', upToDate: '最新', aheadBehind: '先行 {ahead}、遅れ {behind}', stage: 'ステージ', unstage: 'ステージ解除', discard: '変更を破棄', confirm: '確認', cancel: 'キャンセル', checkout: 'チェックアウト', localBranches: 'ローカルブランチ', remoteBranches: 'リモートブランチ', tracking: '追跡', deleteQuestion: '削除しますか？', force: '強制', renameSuccess: '名前を変更しました', renameFailed: '名前の変更に失敗しました', deleteSuccess: 'ブランチを削除しました', deleteFailed: '削除に失敗しました', checkoutFailed: 'チェックアウトに失敗しました', merge: 'マージ', newBranch: '新しいブランチ', stashes: 'スタッシュ', stashAllChanges: 'すべての変更をスタッシュ', noStashes: 'スタッシュはありません', noStashesDesc: 'まだ変更をスタッシュしていません。', apply: '適用', pop: 'Pop', drop: '削除', stashSaveSuccess: '変更をスタッシュしました', stashSaveFailed: 'スタッシュに失敗しました', applyFailed: '適用に失敗しました', popFailed: 'Popに失敗しました', dropSuccess: 'スタッシュを削除しました', dropFailed: 'スタッシュの削除に失敗しました', tags: 'タグ', tagCount: '{count}個のタグ', noTags: 'タグはありません', tagHint: 'リリースポイントを示すタグをコミットから作成します。', lightweightTag: '軽量タグ', remotes: 'リモート', remoteCount: '{count}個のリモート', noRemotes: 'リモートは設定されていません', remoteHint: 'このリポジトリをfetch・pushするにはリモートを追加してください。', fetchUrl: 'Fetch', pushUrl: 'Push', notConfigured: '未設定', successful: '成功', failed: '失敗', commitSuccess: 'コミットしました', pushSuccess: 'プッシュしました', pushFailed: 'プッシュに失敗しました', commitFailed: 'コミットに失敗しました', undo: '元に戻す', undoConfirm: '最後のコミットを元に戻し、作業ディレクトリの変更を保持しますか？', undoSuccess: '元に戻しました', undoFailed: '元に戻す操作に失敗しました',
  },
  Korean: {
    graph: '그래프', message: '메시지', author: '작성자', date: '날짜', hash: '해시', loading: '로드 중...', idle: '대기 중', copyCommand: '명령 복사', clear: '지우기', collapse: '접기', expand: '펼치기', terminal: '터미널', noOperations: 'Git 작업을 실행하면 CLI 출력이 표시됩니다.', gitCommand: 'Git 명령', output: '출력', history: '기록', problems: '문제', executeHint: 'Execute (Enter)를 누르면 Git 명령이 실행됩니다', operationInfo: '작업 정보', stageChanges: '변경사항 스테이징', stageChangesDesc: 'Working Tree의 변경사항을 Staging Area(index)로 이동합니다.', gitFlow: 'Git 흐름', affectedFiles: '영향받은 파일', noAffectedFiles: '영향받은 파일 없음', status: '상태', upToDate: '최신 상태', aheadBehind: '앞섬 {ahead}, 뒤처짐 {behind}', stage: '스테이지', unstage: '스테이지 해제', discard: '변경사항 폐기', confirm: '확인', cancel: '취소', checkout: '체크아웃', localBranches: '로컬 브랜치', remoteBranches: '원격 브랜치', tracking: '추적', deleteQuestion: '삭제하시겠습니까?', force: '강제', renameSuccess: '이름 변경 성공', renameFailed: '이름 변경 실패', deleteSuccess: '브랜치 삭제됨', deleteFailed: '삭제 실패', checkoutFailed: '체크아웃 실패', merge: '병합', newBranch: '새 브랜치', stashes: '스태시', stashAllChanges: '모든 변경사항 스태시', noStashes: '스태시 없음', noStashesDesc: '아직 변경사항을 스태시하지 않았습니다.', apply: '적용', pop: 'Pop', drop: '삭제', stashSaveSuccess: '변경사항을 스태시했습니다', stashSaveFailed: '스태시 실패', applyFailed: '적용 실패', popFailed: 'Pop 실패', dropSuccess: '스태시 삭제됨', dropFailed: '스태시 삭제 실패', tags: '태그', tagCount: '태그 {count}개', noTags: '태그 없음', tagHint: '릴리스 지점을 표시할 태그를 커밋에서 만드세요.', lightweightTag: '경량 태그', remotes: '원격', remoteCount: '원격 {count}개', noRemotes: '설정된 원격 없음', remoteHint: '이 저장소를 fetch하고 push하려면 원격을 추가하세요.', fetchUrl: 'Fetch', pushUrl: 'Push', notConfigured: '설정되지 않음', successful: '성공', failed: '실패', commitSuccess: '커밋 성공', pushSuccess: 'Push 성공', pushFailed: 'Push 실패', commitFailed: '커밋 실패', undo: '되돌리기', undoConfirm: '마지막 커밋을 되돌리고 작업 디렉터리의 변경사항을 유지하시겠습니까?', undoSuccess: '되돌리기 성공', undoFailed: '되돌리기 실패',
  },
  Chinese: {
    graph: '图表', message: '消息', author: '作者', date: '日期', hash: '哈希', loading: '加载中...', idle: '空闲', copyCommand: '复制命令', clear: '清除', collapse: '收起', expand: '展开', terminal: '终端', noOperations: '执行 Git 操作后将在此显示 CLI 输出。', gitCommand: 'Git 命令', output: '输出', history: '历史', problems: '问题', executeHint: '按下 Execute (Enter) 后执行 Git 命令', operationInfo: '操作信息', stageChanges: '暂存更改', stageChangesDesc: '将更改从 Working Tree 移动到 Staging Area (index)。', gitFlow: 'Git 流程', affectedFiles: '受影响的文件', noAffectedFiles: '没有受影响的文件', status: '状态', upToDate: '已是最新', aheadBehind: '领先 {ahead}，落后 {behind}', stage: '暂存', unstage: '取消暂存', discard: '放弃更改', confirm: '确认', cancel: '取消', checkout: '检出', localBranches: '本地分支', remoteBranches: '远程分支', tracking: '跟踪', deleteQuestion: '删除？', force: '强制', renameSuccess: '重命名成功', renameFailed: '重命名失败', deleteSuccess: '分支已删除', deleteFailed: '删除失败', checkoutFailed: '检出失败', merge: '合并', newBranch: '新分支', stashes: '储藏', stashAllChanges: '储藏所有更改', noStashes: '没有储藏', noStashesDesc: '您还没有储藏任何更改。', apply: '应用', pop: 'Pop', drop: '删除', stashSaveSuccess: '已储藏更改', stashSaveFailed: '储藏失败', applyFailed: '应用失败', popFailed: 'Pop 失败', dropSuccess: '储藏已删除', dropFailed: '删除储藏失败', tags: '标签', tagCount: '{count} 个标签', noTags: '没有标签', tagHint: '从提交创建标签以标记发布节点。', lightweightTag: '轻量标签', remotes: '远程', remoteCount: '{count} 个远程', noRemotes: '未配置远程', remoteHint: '添加远程以 fetch 和 push 此仓库。', fetchUrl: 'Fetch', pushUrl: 'Push', notConfigured: '未配置', successful: '成功', failed: '失败', commitSuccess: '提交成功', pushSuccess: 'Push 成功', pushFailed: 'Push 失败', commitFailed: '提交失败', undo: '撤销', undoConfirm: '撤销最后一次提交并保留工作目录中的更改？', undoSuccess: '撤销成功', undoFailed: '撤销失败',
  },
};

const expectedKeys = new Set<string>(UI_KEYS);
for (const [language, dictionary] of Object.entries(UI_TRANSLATIONS)) {
  const actualKeys = new Set(Object.keys(dictionary));
  if (actualKeys.size !== expectedKeys.size || UI_KEYS.some((key) => !actualKeys.has(key))) {
    throw new Error(`Missing UI translation key(s) for ${language}`);
  }
}

export function useUiTranslation() {
  const language = useSettingsStore((state) => state.settings.general.language);
  return (key: UiKey, values?: Record<string, string | number>) => {
    let value = UI_TRANSLATIONS[language][key];
    for (const [name, replacement] of Object.entries(values ?? {})) {
      value = value.replace(`{${name}}`, String(replacement));
    }
    return value;
  };
}